package ejercicio;
// Generated 19 oct. 2022 14:24:10 by Hibernate Tools 6.0.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Medicos generated by hbm2java
 */
public class Medicos implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private String dni;
	private Set citases = new HashSet(0);
	private Set pacienteses = new HashSet(0);

	public Medicos() {
	}

	public Medicos(String nombre, String apellido1, String apellido2, String dni) {
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.dni = dni;
	}

	public Medicos(String nombre, String apellido1, String apellido2, String dni, Set citases, Set pacienteses) {
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.dni = dni;
		this.citases = citases;
		this.pacienteses = pacienteses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public Set getCitases() {
		return this.citases;
	}

	public void setCitases(Set citases) {
		this.citases = citases;
	}

	public Set getPacienteses() {
		return this.pacienteses;
	}

	public void setPacienteses(Set pacienteses) {
		this.pacienteses = pacienteses;
	}

	@Override
	public String toString() {
		return "Medicos [id=" + id + ", nombre=" + nombre + ", apellido1=" + apellido1 + ", apellido2=" + apellido2
				+ ", dni=" + dni + "]";
	}

}
