package ejercicio;
// Generated 19 oct. 2022 14:24:10 by Hibernate Tools 6.0.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Pacientes generated by hbm2java
 */
public class Pacientes implements java.io.Serializable {

	private Integer id;
	private Medicos medicos;
	private String nombre;
	private String dni;
	private Set citases = new HashSet(0);

	public Pacientes() {
	}

	public Pacientes(Medicos medicos, String nombre, String dni) {
		this.medicos = medicos;
		this.nombre = nombre;
		this.dni = dni;
	}

	public Pacientes(Medicos medicos, String nombre, String dni, Set citases) {
		this.medicos = medicos;
		this.nombre = nombre;
		this.dni = dni;
		this.citases = citases;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Medicos getMedicos() {
		return this.medicos;
	}

	public void setMedicos(Medicos medicos) {
		this.medicos = medicos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public Set getCitases() {
		return this.citases;
	}

	public void setCitases(Set citases) {
		this.citases = citases;
	}

	@Override
	public String toString() {
		return "Pacientes [id=" + id + "idMedico=" + medicos.getId() +", nombre=" + nombre + ", dni=" + dni + "]";
	}

}
